name: K6 load test
on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: step 3 - Executar Múltiplos Testes K6
        uses: grafana/k6-action@v0.2.0
        with:
          filename:

      - name: step 4 - Executar cada script K6 individualmente (Recomendado para scripts distintos)
        run: cd modulo_4 && k6 run modulo_4/*.js
