name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - run k6 load test (aula 24)
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: modulo_4/aula_24_ex2.js

      - name: step 3 - run k6 load test (aula 27)
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: modulo_4/aula_27_ex1.js

      - run: ls & mkdir report & mv report_aula_24.html report & mv report_aula_27.html report
      
      - name: step 4 - upload artifact
        uses: actions/upload-artifact@v4     # https://github.com/marketplace/actions/upload-a-build-artifact#usage
        with: 
          name: relatorio de testes de performance
          path: report
      