name: K6 load test
on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Run all k6 tests in modulo_4
        run: |
          for file in modulo_4/*.js; do
            echo "Running $file"
            k6 run "$file"
          done
